name: 🐛 Bug Report
description: Create a report to help us improve SliCLI
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please search existing issues first to make sure this hasn't been reported already.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Open file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened instead?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      value: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04, Windows 11]
        - SliCLI version: [run `slicli --version`]
        - Go version: [run `go version`]
        - Browser: [if relevant]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your slicli.toml configuration (remove any sensitive data)
      render: toml
      placeholder: |
        [server]
        host = "localhost"
        port = 1000
        
        [theme]
        name = "default"

  - type: textarea
    id: logs
    attributes:
      label: Error logs or output
      description: Any relevant error messages or command output
      render: shell
      placeholder: Paste error logs here...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Screenshots, related issues, potential solutions, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have tested with the latest version of SliCLI
          required: false