name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

    - name: Test
      run: |
        go mod download
        go test -v ./...

    - name: Build
      run: |
        make build
        make build-plugins

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest