name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        # Set binary name
        BINARY_NAME="slicli"
        if [ "$GOOS" = "windows" ]; then
          BINARY_NAME="slicli.exe"
        fi
        
        # Build
        go build -ldflags="-s -w" -o "$BINARY_NAME" ./cmd/slicli
        
        # Create archive
        if [ "$GOOS" = "windows" ]; then
          zip "slicli-${{ matrix.goos }}-${{ matrix.goarch }}.zip" "$BINARY_NAME"
        else
          tar -czf "slicli-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz" "$BINARY_NAME"
        fi

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.tar.gz
          *.zip